apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginx-port-status
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nmap
            image: instrumentisto/nmap
            imagePullPolicy: IfNotPresent
            command: 
            - /bin/sh
            - -c
            - echo 'ClusterIP status:'; nmap -p 80 10.101.152.62 --script=http-headers; echo '--------------------------------------------------'; echo 'NodePort status:'; nmap -p 30010 10.156.0.28 --script=http-headers 
          restartPolicy: OnFailure
      backoffLimit: 4
