apiVersion: batch/v1
kind: Job
metadata:
  name: curl-clusterip
spec:
  template:
    spec:
      containers:
      - name: curl
        image: curlimages/curl
        command: ['curl', '10.101.152.62']
      restartPolicy: OnFailure
  backoffLimit: 4