- name: Get Cluster information
  kubernetes.core.k8s_cluster_info:
  register: api_status



- name: api_status
  debug:
    msg: 
      - "api_status failed - {{ api_status.failed }}"
      - "client version - {{ api_status.version.client }}" 
      - "server kubernetes -  {{ api_status.version.server.kubernetes }}"

      