replicaCount: 1
revisionHistoryLimit: 1
image: 
  repository: registry.gitlab.com/devops6485606/frontend 
  tag: latest
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
service:
  name: frontend
  type: ClusterIP
  servicePort: 80 # the port where nginx serves its traffic

dnsName: esemerenko.dns.navy 
