apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.container.image }}
        ports:
        - containerPort: 8080
          name: http-web-svc
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
        env:
          - name: WORDPRESS_DATABASE_HOST
            value: {{ .Values.wpDbHost }}
          - name: WORDPRESS_DATABASE_PASSWORD
            value: {{ .Values.wpDbPassword }}
          - name: WORDPRESS_DATABASE_USER
            value: {{ .Values.wpDbUser }}
          - name: WORDPRESS_DATABASE_NAME
            value: {{ .Values.wpDbName }}
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
