---

- name: creating a empty file /etc/iaac with rigths 0500
  hosts: iaas
  become: yes
  roles:
    - create_file

   


- name: fetch a linux distro name_version
  hosts: 
    all
  gather_facts: yes
  become: no
  roles:
    - fetch_linux_distro_name_version



