apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: frontend
spec:
  ports:
  - name: http
    targetPort: {{ .Values.service.servicePort }}
    port: 30444
  type: ClusterIP
  selector:
    app: frontend
