apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: backend
spec:
  ports:
  - name: http
    targetPort: {{ .Values.service.servicePort }}
    port: 30555
  type: ClusterIP   
  selector:
    app: backend
