
- name: keyless-only ssh
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: PasswordAuthentication no

- name: Install unattended-upgrades
  ansible.builtin.apt:
    pkg:
    - unattended-upgrades
    state: present
    update_cache: yes

- name: Ensure SSH root login is disabled
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: PermitRootLogin no


 